/* Products API — GET (public), POST/PATCH/DELETE (auth required) */
const { verifySession, cors } = require('./_auth');
const { readBlob, writeBlob } = require('./_blob');

const PRODUCTS_PATH = 'data/maxwell-products.json';

const SEED_PRODUCTS = [
  { id:'all-purpose-cleaner', name:'All Purpose Cleaner', cat:'household', sub:'Versatile Multi-Surface Cleaning Solution', price:89.99, was:109.99, size:'500ml', rating:4.8, reviews:124, badge:'Bestseller', img:'assets/products/all-purpose-cleaner.jpg', benefits:['Cuts grease & grime','Cleans kitchens, bathrooms & counters','Leaves surfaces fresh & streak-free','Safe on tiles, stainless steel & sealed surfaces'], desc:'A versatile multi-surface cleaning solution designed to cut through grease, dirt and grime — leaving every washable surface sparkling clean and fresh every time.', scent:'Fresh Clean', sku:'APC-500-001', stock:48, lowStockThreshold:10, status:'active', variants:[{name:'500ml',price:89.99,stock:48},{name:'1L',price:149.99,stock:22}], createdAt:1705276800000, updatedAt:1730419200000 },
  { id:'tile-cleaner', name:'Tile Cleaner', cat:'household', sub:'Powerful Floor & Tile Cleaning Solution', price:94.99, was:null, size:'5L', rating:4.7, reviews:98, badge:null, img:'assets/products/tile-cleaner.jpg', benefits:['Removes tough stains','Cuts grease & grime','Fresh clean finish','Suitable for ceramic & porcelain tiles'], desc:'Powerful cleaning solution formulated to remove tough stains, dirt, grease and soap scum from floor and wall tiles — leaving surfaces sparkling with a fresh finish.', scent:'Sparkling Fresh', sku:'TLC-5L-002', stock:62, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:94.99,stock:62}], createdAt:1705276800000, updatedAt:1729555200000 },
  { id:'carpet-upholstery-shampoo', name:'Carpet & Upholstery Shampoo', cat:'household', sub:'Deep Cleaning Fabric & Carpet Care', price:129.99, was:149.99, size:'5L', rating:4.9, reviews:76, badge:'Bestseller', img:'assets/products/carpet-upholstery-shampoo.png', benefits:['Lifts dirt & stubborn stains','Refreshes carpets & upholstery','Low-foam fresh clean finish','Suitable for rugs, sofas & fabric seats'], desc:'A powerful shampoo specially formulated to remove dirt, stains and embedded grime from carpets, rugs and upholstered surfaces — leaving them cleaner, brighter and fresh-smelling.', scent:'Fresh Linen', sku:'CUS-5L-003', stock:7, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:129.99,stock:7}], createdAt:1707264000000, updatedAt:1730764800000 },
  { id:'linen-spray', name:'Linen Spray', cat:'household', sub:'Fresh Linen Fragrance & Fabric Refresh', price:99.99, was:null, size:'500ml', rating:4.8, reviews:61, badge:'New', img:'assets/products/linen-spray.jpg', benefits:['Refreshes linen & fabrics instantly','Helps neutralize unwanted odours','Long-lasting fresh scent','For bedding, curtains & upholstery'], desc:'A fabric freshening spray formulated to refresh linen, bedding, curtains and soft furnishings — eliminating odours while leaving fabrics smelling clean, crisp and pleasantly fresh.', scent:'Fresh Linen', sku:'LNS-500-004', stock:24, lowStockThreshold:10, status:'active', variants:[{name:'500ml',price:99.99,stock:24}], createdAt:1709251200000, updatedAt:1728950400000 },
  { id:'hand-surface-sanitiser', name:'Hand & Surface Sanitiser', cat:'sanitiser', sub:'Isopropyl Alcohol 85% — Kills 99.9% of germs', price:149.99, was:null, size:'5L', rating:4.9, reviews:210, badge:'Bestseller', img:'assets/products/hand-surface-sanitiser.jpg', benefits:['Kills 99.9% of germs & bacteria','Fast drying & non-sticky','No-rinse formula','Surface friendly'], desc:'High-strength hand and surface sanitiser formulated with 85% Isopropyl Alcohol to kill 99.9% of germs and bacteria. Fast-drying and non-sticky — suitable for hands and a wide range of hard surfaces.', scent:'85% IPA', sku:'HSS-5L-005', stock:5, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:59.99,stock:45},{name:'5L',price:149.99,stock:5}], createdAt:1704844800000, updatedAt:1731024000000 },
  { id:'isopropyl-alcohol', name:'Isopropyl Alcohol 99.99%', cat:'sanitiser', sub:'Fast Drying Cleaning & Disinfecting Solution', price:179.99, was:199.99, size:'5L', rating:4.9, reviews:143, badge:'High Purity', img:'assets/products/isopropyl-alcohol.jpg', benefits:['Quick evaporation & fast drying','Removes grease, dirt & residue','Safe for glass, electronics & equipment','Leaves a clean streak-free finish'], desc:'A fast-evaporating 99.99% Isopropyl Alcohol cleaning solution that removes grease, grime and residue from hard surfaces and equipment — drying quickly without leaving heavy residue.', scent:'99.99% IPA', sku:'IPA-5L-006', stock:22, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:89.99,stock:30},{name:'5L',price:179.99,stock:22}], createdAt:1705017600000, updatedAt:1729382400000 },
  { id:'tyre-shine', name:'Tyre Shine', cat:'car', sub:'Deep Black Shine & Long-Lasting Protection', price:119.99, was:null, size:'5L', rating:4.7, reviews:88, badge:null, img:'assets/products/tyre-shine.jpg', benefits:['Restores deep black tyre finish','Instant glossy shine','Helps protect against cracking & fading','Repels dust & road grime'], desc:'A premium tyre dressing formulated to restore a rich black appearance and a clean, glossy finish — enhancing the look of tyres while protecting against dryness, dullness and everyday road grime.', scent:null, sku:'TYS-5L-007', stock:31, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:59.99,stock:15},{name:'5L',price:119.99,stock:31}], createdAt:1705708800000, updatedAt:1730160000000 },
  { id:'tyre-dash-shine', name:'Tyre & Dash Shine', cat:'car', sub:'Interior & Exterior Dressing Combo', price:129.99, was:null, size:'5L', rating:4.6, reviews:55, badge:null, img:'assets/products/tyre-dash-shine.jpg', benefits:['Shines tyres & interior plastics','Restores faded black trim','Non-greasy satin finish','UV protection built-in'], desc:'A versatile 2-in-1 dressing that delivers a clean, satin finish on both tyres and interior plastics — restoring faded trim and protecting against UV damage and everyday wear.', scent:null, sku:'TDS-5L-008', stock:18, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:69.99,stock:20},{name:'5L',price:129.99,stock:18}], createdAt:1707091200000, updatedAt:1729728000000 },
  { id:'wash-up-liquid-green', name:'Wash-Up Liquid (Green)', cat:'household', sub:'Heavy-Duty Dishwashing & Degreasing Liquid', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/wash-up-liquid-green.jpg', benefits:['Cuts through grease fast','Rich lather formula','Gentle on hands','For dishes, pots & surfaces'], desc:'A powerful green dishwashing liquid formulated to cut through grease and food residue — leaving dishes, pots and kitchen surfaces clean and fresh with minimal effort.', scent:'Fresh Green', sku:'WUL-5L-009', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'sanitizers', name:'Sanitizers', cat:'household', sub:'Multi-Surface Sanitizing Solution', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/sanitizers.jpg', benefits:['Kills germs & bacteria','Safe on hard surfaces','Quick-drying formula','No harsh residue'], desc:'A reliable sanitizing solution for everyday use on hard surfaces — effectively eliminating germs, bacteria and common pathogens to keep your home clean and safe.', scent:'Clean Fresh', sku:'SAN-5L-010', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'sani-pine', name:'Sani-Pine', cat:'household', sub:'Pine-Scented Disinfectant Cleaner', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/sani-pine.jpg', benefits:['Disinfects & deodorises','Classic pine fragrance','Kills household germs','For floors, toilets & hard surfaces'], desc:'A pine-scented disinfectant cleaner that sanitises and deodorises floors, toilets and hard surfaces — leaving behind a fresh, clean pine fragrance.', scent:'Pine Fresh', sku:'SNP-5L-011', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'floor-shine-high-traffic', name:'Floor Shine High Traffic', cat:'household', sub:'High-Gloss Floor Polish for Heavy-Use Areas', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/floor-shine-high-traffic.jpg', benefits:['High-gloss mirror finish','Durable in heavy traffic areas','Protects & seals floor surfaces','Suitable for vinyl, tiles & linoleum'], desc:'A premium floor polish specially formulated for high-traffic areas — delivering a brilliant, long-lasting gloss finish while protecting floor surfaces from daily wear and scuffing.', scent:null, sku:'FSH-5L-012', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'shower-gel', name:'Shower Gel', cat:'household', sub:'Gentle Moisturising Body Wash', price:0, was:null, size:'500ml', rating:4.7, reviews:0, badge:null, img:'assets/products/shower-gel.jpg', benefits:['Rich lather & smooth rinse','Moisturises skin','Pleasant fragrance','Gentle on all skin types'], desc:'A gentle, moisturising shower gel formulated with a rich lather that cleanses the skin effectively while leaving it feeling soft, smooth and refreshed.', scent:'Fresh Breeze', sku:'SHG-500-013', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'500ml',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'sulphuric-acid', name:'Sulphuric Acid', cat:'household', sub:'Drain & Blockage Clearing Solution', price:0, was:null, size:'5L', rating:4.6, reviews:0, badge:null, img:'assets/products/sulphuric-acid.jpg', benefits:['Clears blocked drains fast','Breaks down organic blockages','Industrial strength formula','For drains, sewers & pipes'], desc:'A high-strength sulphuric acid solution for clearing blocked drains and removing organic build-up in pipes and sewers. Use with caution — follow safety instructions carefully.', scent:null, sku:'SUL-5L-014', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'toilet-bowl-cleaner', name:'Toilet Bowl Cleaner', cat:'household', sub:'Powerful Toilet Disinfectant & Descaler', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/toilet-bowl-cleaner.jpg', benefits:['Removes limescale & stains','Disinfects & deodorises','Clings to bowl surface','Fresh clean scent'], desc:'A powerful toilet bowl cleaner that removes limescale, stains and bacteria — disinfecting and deodorising the bowl while leaving a fresh, clean scent.', scent:'Clean Citrus', sku:'TBC-5L-015', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'thick-bleach', name:'Thick Bleach (Domestos Type)', cat:'household', sub:'Heavy-Duty Thick Bleach Disinfectant', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/thick-bleach.jpg', benefits:['Kills 99.9% of germs','Thick formula clings to surfaces','Whitens & disinfects','For toilets, drains & hard surfaces'], desc:'A thick, heavy-duty bleach disinfectant that clings to surfaces for extended contact time — killing 99.9% of germs, whitening surfaces and eliminating tough stains and odours.', scent:'Clean Bleach', sku:'TBL-5L-016', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'oxy-o2', name:'Oxy O2 (Vanish Type)', cat:'household', sub:'Oxygen-Powered Stain Remover & Fabric Brightener', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/oxy-o2.jpg', benefits:['Removes tough stains on contact','Brightens & whitens fabrics','Oxygen-activated formula','Safe on colours & whites'], desc:'An oxygen-powered stain remover formulated to lift tough stains from fabrics, carpets and surfaces — brightening and refreshing without the harsh effects of chlorine bleach.', scent:null, sku:'OXY-5L-017', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'industrial-washing-powder', name:'Industrial Washing Powder', cat:'household', sub:'Heavy-Duty Laundry Powder for Commercial Use', price:0, was:null, size:'25kg', rating:4.7, reviews:0, badge:null, img:'assets/products/industrial-washing-powder.jpg', benefits:['Heavy-duty cleaning power','For commercial laundry use','Removes tough stains & grime','High-foaming formula'], desc:'A heavy-duty industrial washing powder designed for commercial and high-volume laundry use — delivering powerful cleaning performance to remove tough stains, grease and grime.', scent:'Clean Fresh', sku:'IWP-25K-018', stock:30, lowStockThreshold:5, status:'active', variants:[{name:'25kg',price:0,stock:30}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'high-foaming-hand-washing-powder', name:'High Foaming Hand Washing Powder', cat:'household', sub:'Premium Hand-Wash Laundry Powder', price:0, was:null, size:'5kg', rating:4.7, reviews:0, badge:null, img:'assets/products/high-foaming-hand-washing-powder.jpg', benefits:['High foam for hand washing','Removes stains effectively','Gentle on fabrics','Pleasant fresh scent'], desc:'A high-foaming hand washing powder specially formulated for hand laundry — producing a rich lather to lift dirt and stains while remaining gentle on fabrics and skin.', scent:'Spring Fresh', sku:'HFP-5K-019', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5kg',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'bio-ultra', name:'Bio Ultra (Bio Classic Type)', cat:'household', sub:'Biological Enzyme Laundry Liquid', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/bio-ultra.jpg', benefits:['Enzyme-powered stain removal','Works in cool wash temperatures','Breaks down proteins & oils','Suitable for all fabrics'], desc:'A biological enzyme laundry liquid that uses natural enzymes to break down protein-based stains, grease and oils — working effectively even at low wash temperatures.', scent:'Fresh Clean', sku:'BIO-5L-020', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'metal-polish', name:'Metal Polish', cat:'household', sub:'Multi-Metal Shine & Protection Polish', price:0, was:null, size:'1L', rating:4.7, reviews:0, badge:null, img:'assets/products/metal-polish.jpg', benefits:['Restores shine to all metals','Removes tarnish & oxidation','Leaves a protective coating','For stainless steel, chrome & brass'], desc:'A premium metal polish formulated to restore shine and remove tarnish, rust and oxidation from stainless steel, chrome, brass and other metal surfaces — leaving a brilliant finish with protective coating.', scent:null, sku:'MTP-1L-021', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'mop-and-shine', name:'Mop & Shine', cat:'household', sub:'Floor Cleaner & Shine in One', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/mop-and-shine.jpg', benefits:['Cleans & shines in one step','Long-lasting floor protection','Pleasant fragrance','For tiles, vinyl & sealed floors'], desc:'A dual-action floor cleaner and shine product that cleans and polishes in a single application — leaving floors sparkling, protected and smelling fresh.', scent:'Fresh Citrus', sku:'MAS-5L-022', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'pine-gel', name:'Pine Gel', cat:'household', sub:'Pine-Scented Heavy-Duty Cleaning Gel', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/pine-gel.jpg', benefits:['Powerful cleaning & disinfection','Classic pine fragrance','Gel formula clings to surfaces','For floors, tiles & bathrooms'], desc:'A thick pine-scented cleaning gel that clings to surfaces for deep cleaning and disinfection — leaving a powerful clean and a long-lasting fresh pine fragrance throughout the home.', scent:'Pine', sku:'PNG-5L-023', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'drain-cleaner', name:'Drain Cleaner', cat:'household', sub:'Fast-Acting Drain Unblocking Solution', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/drain-cleaner.jpg', benefits:['Clears blocked drains fast','Dissolves hair, grease & organic matter','Works in sinks, showers & baths','Prevents future blockages'], desc:'A fast-acting drain cleaning solution formulated to dissolve hair, grease and organic blockages in sinks, showers and pipes — restoring full drainage quickly and effectively.', scent:null, sku:'DRC-5L-024', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'fabric-softener', name:'Fabric Softener (Comfort Type)', cat:'household', sub:'Long-Lasting Fabric Conditioner & Softener', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/fabric-softener.jpg', benefits:['Softens & conditions fabrics','Reduces static & wrinkles','Long-lasting fresh scent','Suitable for all fabric types'], desc:'A premium fabric softener and conditioner that leaves laundry feeling soft, fresh and static-free — delivering long-lasting fragrance and gentle care for all fabric types.', scent:'Spring Blossom', sku:'FSO-5L-025', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'floor-stripper', name:'Floor Stripper', cat:'household', sub:'Heavy-Duty Floor Polish & Wax Remover', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/floor-stripper.jpg', benefits:['Strips old wax & floor polish','Prepares surfaces for re-polishing','Fast-acting formula','Suitable for vinyl, tiles & linoleum'], desc:'A powerful floor stripping solution that removes old wax, polish and build-up from hard floor surfaces — preparing them for a fresh application of floor polish or sealer.', scent:null, sku:'FLS-5L-026', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'furniture-polish', name:'Furniture Polish', cat:'household', sub:'Shine & Protect Wood & Furniture Polish', price:0, was:null, size:'500ml', rating:4.8, reviews:0, badge:null, img:'assets/products/furniture-polish.jpg', benefits:['Restores shine to wood furniture','Protects against dust & scratches','Pleasant fresh wood scent','For tables, cabinets & shelves'], desc:'A quality furniture polish that cleans, shines and protects wood and laminate furniture — restoring a natural lustre while leaving a pleasant fresh scent and a protective barrier.', scent:'Fresh Wood', sku:'FPL-500-027', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'500ml',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'hard-surface-cleaner', name:'Hard Surface Cleaner (Handy Andy Type)', cat:'household', sub:'All-Purpose Cream Cleaner for Tough Surfaces', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/hard-surface-cleaner.jpg', benefits:['Removes stubborn marks & stains','Gentle abrasive cream formula','Safe on most hard surfaces','For kitchens, bathrooms & appliances'], desc:'An all-purpose cream cleaner formulated to remove tough marks, stains and grease from hard surfaces — using a gentle abrasive formula that cleans without scratching kitchens, bathrooms and appliances.', scent:'Clean Fresh', sku:'HSC-5L-028', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'laundry-liquid', name:'Laundry Liquid (OMO Auto Type)', cat:'household', sub:'Automatic Machine Washing Liquid', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/laundry-liquid.jpg', benefits:['For front & top loader machines','Powerful stain removal','Fresh clean scent','Low-foam auto formula'], desc:'A concentrated automatic laundry liquid formulated for front and top loader washing machines — delivering powerful stain removal and a long-lasting fresh scent with every wash.', scent:'Spring Fresh', sku:'LLQ-5L-029', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'overall-washing-powder', name:'Overall Washing Powder', cat:'household', sub:'Industrial-Strength Laundry Washing Powder', price:0, was:null, size:'10kg', rating:4.7, reviews:0, badge:null, img:'assets/products/overall-washing-powder.jpg', benefits:['Industrial cleaning power','Removes heavy soiling & grease','High-foaming formula','For overalls, workwear & heavy fabrics'], desc:'A heavy-duty washing powder designed for cleaning overalls, workwear and heavily soiled fabrics — cutting through grease, dirt and industrial grime to deliver a thorough clean.', scent:'Clean Fresh', sku:'OWP-10K-030', stock:30, lowStockThreshold:5, status:'active', variants:[{name:'10kg',price:0,stock:30}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'bleach-jik-type', name:'Bleach (Jik Type)', cat:'household', sub:'Multi-Purpose Household Bleach', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/bleach-jik-type.jpg', benefits:['Whitens & disinfects','Kills germs & bacteria','Removes tough stains','For laundry, toilets & surfaces'], desc:'A powerful household bleach that whitens, disinfects and removes tough stains from laundry, toilets and hard surfaces — killing germs and bacteria for a hygienic clean.', scent:'Clean Bleach', sku:'BLJ-5L-031', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'deo-blocks', name:'Deo Blocks', cat:'household', sub:'Long-Lasting Toilet & Urinal Deodoriser Blocks', price:0, was:null, size:'1kg', rating:4.7, reviews:0, badge:null, img:'assets/products/deo-blocks.jpg', benefits:['Long-lasting fragrance','Neutralises unpleasant odours','For toilets & urinals','Slow-release formula'], desc:'Slow-release deodoriser blocks formulated for toilets and urinals — neutralising unpleasant odours and delivering a long-lasting fresh fragrance in bathroom and restroom environments.', scent:'Fresh Mint', sku:'DEO-1K-032', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'1kg',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'bubble-bath', name:'Bubble Bath', cat:'household', sub:'Luxurious Foaming Bubble Bath Formula', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/bubble-bath.jpg', benefits:['Rich, long-lasting bubbles','Gentle on skin','Pleasant fragrance','For adults & children'], desc:'A luxurious foaming bubble bath formulated to create a rich, long-lasting lather — gentle on skin with a pleasant fragrance that makes bath time a relaxing and enjoyable experience.', scent:'Ocean Fresh', sku:'BBT-5L-033', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'dispenser-hand-soap-pink', name:'Dispenser Hand Soap Pink', cat:'household', sub:'Gentle Pink Hand Soap for Dispensers', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/dispenser-hand-soap-pink.jpg', benefits:['Gentle & moisturising formula','For all dispenser types','Pleasant light fragrance','Leaves hands soft & clean'], desc:'A gentle pink hand soap formulated for soap dispensers in kitchens, bathrooms and commercial settings — effectively cleansing hands while leaving skin feeling soft and fresh.', scent:'Light Floral', sku:'DHS-5L-034', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'dribrite-floor-shine', name:'Dribrite Floor Shine', cat:'household', sub:'High-Gloss Floor Polish & Protector', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/dribrite-floor-shine.jpg', benefits:['High-gloss mirror finish','Durable floor protection','Quick-drying formula','For vinyl, tiles & sealed wood'], desc:'A premium floor polish delivering a brilliant high-gloss finish with long-lasting protection — quick-drying and suitable for vinyl, tiles and sealed floor surfaces in homes and commercial spaces.', scent:null, sku:'DFS-5L-035', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'industrial-overall-washing-powders', name:'Overall Washing Powders', cat:'industrial', sub:'Bulk Industrial Laundry Washing Powder', price:0, was:null, size:'25kg', rating:4.7, reviews:0, badge:null, img:'assets/products/industrial-overall-washing-powders.jpg', benefits:['Bulk commercial supply','Removes heavy soiling & grease','High-foaming formula','For overalls, workwear & industrial fabrics'], desc:'A bulk industrial laundry washing powder available in large quantities — designed for commercial laundromats, factories and industrial facilities requiring high-volume washing power.', scent:'Clean Fresh', sku:'OWP-25K-036', stock:20, lowStockThreshold:5, status:'active', variants:[{name:'25kg',price:0,stock:20}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'heavy-duty-degreaser', name:'Heavy Duty Degreaser', cat:'industrial', sub:'Industrial-Strength Degreasing Solution', price:0, was:null, size:'25L', rating:4.8, reviews:0, badge:null, img:'assets/products/heavy-duty-degreaser.jpg', benefits:['Removes heavy grease & oils','Fast-acting penetrating formula','For machinery, engines & floors','Dilutable for varied applications'], desc:'A powerful industrial-strength degreaser formulated to cut through heavy grease, oil, fuel residue and industrial grime — ideal for use on machinery, engines, workshop floors and industrial equipment.', scent:null, sku:'HDD-25L-037', stock:30, lowStockThreshold:5, status:'active', variants:[{name:'25L',price:0,stock:30}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'hd-degreaser', name:'HD Degreaser', cat:'industrial', sub:'High-Performance Industrial Degreaser', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/hd-degreaser.jpg', benefits:['High-performance degreasing','Penetrates tough grease build-up','Safe on most metals & surfaces','Suitable for workshops & factories'], desc:'An industrial-grade HD degreaser formulated for high-performance grease and oil removal in workshop, factory and manufacturing environments — effective on metals, concrete and most hard surfaces.', scent:null, sku:'HDD-5L-038', stock:40, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:40}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'nr-solvent-degreaser', name:'NR Solvent Degreaser', cat:'industrial', sub:'Non-Residue Solvent-Based Degreaser', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/nr-solvent-degreaser.jpg', benefits:['Leaves no residue after drying','Fast-evaporating solvent formula','For precision equipment & electronics','Removes oils, flux & contaminants'], desc:'A non-residue solvent-based degreaser that evaporates cleanly without leaving residue — ideal for degreasing precision equipment, electronics, electrical components and sensitive machinery.', scent:null, sku:'NRS-5L-039', stock:40, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:40}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'truck-shampoo', name:'Truck Shampoo', cat:'industrial', sub:'Heavy-Duty Vehicle & Truck Wash Shampoo', price:0, was:null, size:'25L', rating:4.7, reviews:0, badge:null, img:'assets/products/truck-shampoo.jpg', benefits:['Removes road grime & diesel soot','High-foaming concentrate','Safe on painted surfaces & chrome','For trucks, buses & heavy vehicles'], desc:'A heavy-duty truck and vehicle wash shampoo specially formulated to remove road grime, diesel soot, mud and heavy soiling from trucks, buses and large commercial vehicles.', scent:'Clean Fresh', sku:'TKS-25L-040', stock:20, lowStockThreshold:5, status:'active', variants:[{name:'25L',price:0,stock:20}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'window-dae-scaler', name:'Window Dae-Scaler', cat:'industrial', sub:'Industrial Window & Glass Scale Remover', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/window-dae-scaler.jpg', benefits:['Removes mineral scale & hard water marks','Leaves glass streak-free','For windows, glass facades & panels','Industrial concentration'], desc:'An industrial-strength window and glass descaler formulated to remove stubborn mineral scale, hard water deposits and calcium build-up from glass surfaces — leaving a clear, streak-free finish.', scent:null, sku:'WDS-5L-041', stock:40, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:40}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'alkaline-washing-powders', name:'Alkaline Washing Powders', cat:'industrial', sub:'High-Alkaline Industrial Cleaning Powder', price:0, was:null, size:'25kg', rating:4.7, reviews:0, badge:null, img:'assets/products/alkaline-washing-powders.jpg', benefits:['High-alkaline formula cuts grease','For industrial laundry & surface cleaning','Removes oils, proteins & heavy soiling','Suitable for commercial washing machines'], desc:'A high-alkaline washing powder designed for industrial laundry and surface cleaning applications — effectively cutting through grease, oils and protein-based soiling in commercial and industrial settings.', scent:'Clean Fresh', sku:'AWP-25K-042', stock:20, lowStockThreshold:5, status:'active', variants:[{name:'25kg',price:0,stock:20}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'alubrite', name:'Alubrite', cat:'industrial', sub:'Aluminium Brightener & Cleaner', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/alubrite.jpg', benefits:['Brightens & cleans aluminium','Removes oxidation & staining','For wheels, tanks & aluminium surfaces','Restores original shine'], desc:'A specialist aluminium brightener and cleaner formulated to remove oxidation, staining and dulling from aluminium surfaces — restoring a bright, clean finish on wheels, tanks and aluminium panels.', scent:null, sku:'ALB-5L-043', stock:40, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:40}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'hf-alubrite', name:'HF Alubrite', cat:'industrial', sub:'High-Foam Aluminium Brightener', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/hf-alubrite.jpg', benefits:['High-foam formula for better coverage','Brightens aluminium fast','For truck tanks & trailers','Removes heavy oxidation'], desc:'A high-foam aluminium brightener delivering improved surface coverage and faster brightening — specially formulated for truck tanks, trailers and large aluminium surfaces requiring a deep clean and restoration.', scent:null, sku:'HFA-5L-044', stock:40, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:40}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'anti-freeze-concentrate', name:'Anti-Freeze Concentrate 96%', cat:'industrial', sub:'High-Concentration Coolant Anti-Freeze', price:0, was:null, size:'25L', rating:4.8, reviews:0, badge:null, img:'assets/products/anti-freeze-concentrate.jpg', benefits:['96% concentrate formula','Protects against freezing & overheating','Compatible with most cooling systems','Extends coolant system life'], desc:'A high-concentration 96% anti-freeze coolant formulated to protect vehicle and industrial cooling systems against freezing, overheating and corrosion — compatible with most radiator and cooling systems.', scent:null, sku:'AFC-25L-045', stock:20, lowStockThreshold:5, status:'active', variants:[{name:'25L',price:0,stock:20}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'hand-cleaner-paste-grit', name:'Hand Cleaner Paste - Grit', cat:'industrial', sub:'Heavy-Duty Grit Hand Cleaner for Workshop Use', price:0, was:null, size:'5kg', rating:4.8, reviews:0, badge:null, img:'assets/products/hand-cleaner-paste-grit.jpg', benefits:['Removes grease, oil & industrial grime','Grit particles for deep scrubbing','Moisturises while it cleans','For mechanics, engineers & factory workers'], desc:'A heavy-duty grit hand cleaner paste formulated for mechanics, engineers and industrial workers — using fine grit particles to deep-clean grease, oil and stubborn industrial grime from hands.', scent:'Clean Fresh', sku:'HCP-5K-046', stock:30, lowStockThreshold:5, status:'active', variants:[{name:'5kg',price:0,stock:30}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'bio-degreaser-specialised', name:'Bio Degreaser Specialised', cat:'industrial', sub:'Biological Enzyme Industrial Degreaser', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/bio-degreaser-specialised.jpg', benefits:['Enzyme-powered biological degreasing','Eco-friendly & biodegradable','Breaks down oils & hydrocarbons','Safe for drains & waterways'], desc:'A specialised biological enzyme degreaser that uses natural bacteria and enzymes to break down oils, fats and hydrocarbons — an eco-friendly, biodegradable alternative for industrial degreasing applications.', scent:null, sku:'BDS-5L-047', stock:40, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:40}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'eco-degreaser-hd-red', name:'Eco Degreaser HD Red', cat:'industrial', sub:'Eco-Friendly Heavy-Duty Red Degreaser', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/eco-degreaser-hd-red.jpg', benefits:['Heavy-duty eco-friendly formula','Biodegradable & low-toxicity','Removes grease & oils effectively','For industrial & commercial use'], desc:'An eco-friendly heavy-duty red degreaser formulated to deliver powerful grease and oil removal while maintaining a low-toxicity, biodegradable profile — suitable for industrial and commercial cleaning applications.', scent:null, sku:'EHD-5L-048', stock:40, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:40}], createdAt:1749513600000, updatedAt:1749513600000 },
  { id:'waterless-car-wash', name:'Waterless Car Wash', cat:'car', sub:'No-Rinse Spray & Wipe Car Cleaning Solution', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/waterless-car-wash.jpg', benefits:['No water or rinsing required','Lifts dirt & dust safely','Leaves a streak-free shine','Saves water & time'], desc:'A waterless car wash spray formulated to safely lift and remove dust, light dirt and grime from vehicle surfaces without water — leaving a clean, streak-free finish with minimal effort.', scent:null, sku:'WCW-5L-049', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1780963200000, updatedAt:1780963200000 },
  { id:'wash-n-wax-pearly-blue', name:"Wash 'N Wax (Pearly Blue)", cat:'car', sub:'Shampoo & Wax Combo for a Showroom Finish', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/wash-n-wax-pearly-blue.jpg', benefits:['Cleans & waxes in one step','Pearlescent blue formula','Leaves a glossy protected finish','Safe on all vehicle paintwork'], desc:"A combined car shampoo and wax solution in a striking pearly blue formula — cleaning and protecting vehicle paintwork in a single wash to leave a brilliant glossy, showroom-quality finish.", scent:'Fresh Blue', sku:'WNW-5L-050', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1780963200000, updatedAt:1780963200000 },
  { id:'foam-3-concentrate', name:'Foam 3 Concentrate', cat:'car', sub:'High-Foam Concentrated Car Wash Shampoo', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/foam-3-concentrate.jpg', benefits:['Ultra-high foam formula','Concentrated — dilutes far','Lifts grime without scratching','Safe on all exterior surfaces'], desc:'A highly concentrated high-foam car wash shampoo that produces a thick, lubricating lather to safely lift and remove road grime, dirt and contaminants from all exterior vehicle surfaces.', scent:null, sku:'FM3-5L-051', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1780963200000, updatedAt:1780963200000 },
  { id:'blue-shampoo', name:'Blue Shampoo', cat:'car', sub:'Premium Blue Car Wash Shampoo', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/blue-shampoo.jpg', benefits:['Rich lather for thorough cleaning','Removes road grime & dirt','pH balanced for safe paint use','Leaves a clean streak-free finish'], desc:'A premium blue car shampoo formulated with a rich lather to thoroughly clean vehicle paintwork — removing road grime, traffic film and dirt while remaining pH balanced and safe on all finishes.', scent:'Fresh Clean', sku:'BLS-5L-052', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1780963200000, updatedAt:1780963200000 },
  { id:'hi-foam-shampoo-pink', name:'Hi Foam Shampoo (Pink)', cat:'car', sub:'High-Foam Pink Car Wash Shampoo', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/hi-foam-shampoo-pink.jpg', benefits:['Extra-high foam formula','Gentle on paint & clear coat','Removes dirt & road film','Pleasant fresh fragrance'], desc:'A vibrant pink high-foam car wash shampoo that generates a thick, cushioning lather to gently clean and remove road film, dirt and light contaminants — safe on all vehicle paint types and clear coats.', scent:'Cherry Fresh', sku:'HFS-5L-053', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1780963200000, updatedAt:1780963200000 },
  { id:'rinseless-wash', name:'Rinseless Wash', cat:'car', sub:'No-Rinse Waterless Car Cleaning Solution', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/rinseless-wash.jpg', benefits:['No rinsing required','Encapsulates & lifts dirt safely','Leaves a slick clean finish','Ideal for indoor & waterless washing'], desc:'A rinseless car wash solution that encapsulates and safely removes dirt and contaminants without the need for rinsing — leaving a clean, smooth finish ideal for indoor detailing or water-restricted environments.', scent:null, sku:'RLW-5L-054', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'5L',price:0,stock:50}], createdAt:1780963200000, updatedAt:1780963200000 },
  { id:'correction-compound', name:'Correction Compound', cat:'car', sub:'Professional Paint Correction & Swirl Remover', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/correction-compound.jpg', benefits:['Removes swirl marks & light scratches','Restores paint clarity & gloss','Professional-grade formula','For all paint types & colours'], desc:'A professional-grade correction compound formulated to remove swirl marks, light scratches and surface oxidation — restoring paint clarity and preparing surfaces for polishing and protection.', scent:null, sku:'CRC-5L-055', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:0,stock:50},{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'easy-gloss-car-polish', name:'Easy Gloss Car Polish', cat:'car', sub:'All-In-One Car Polish & Paint Enhancer', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/easy-gloss-car-polish.jpg', benefits:['Deep gloss & shine finish','Removes light marks & haze','Easy to apply & buff off','Suitable for all paint colours'], desc:'An easy-to-use car polish that enhances paint gloss and clarity in one step — removing light marks, haze and dullness while leaving a brilliant deep shine on all paint types.', scent:null, sku:'EGP-5L-056', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:0,stock:50},{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'claybar', name:'Claybar', cat:'car', sub:'Paint Decontamination & Surface Prep Kit', price:0, was:null, size:'Kit', rating:4.9, reviews:0, badge:null, img:'assets/products/claybar.jpg', benefits:['Removes bonded surface contaminants','Leaves paint slick & smooth','Essential pre-polish step','Includes clay, lubricant & cloths'], desc:'A professional clay bar decontamination kit that removes bonded contaminants, industrial fallout and rail dust from paintwork — leaving surfaces perfectly smooth and ready for polishing or ceramic coating.', scent:null, sku:'CLB-KIT-057', stock:30, lowStockThreshold:5, status:'active', variants:[{name:'Kit',price:0,stock:30}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'quick-detailer', name:'Quick Detailer', cat:'car', sub:'Fast Spray Detailer & Surface Enhancer', price:0, was:null, size:'500ml', rating:4.8, reviews:0, badge:null, img:'assets/products/quick-detailer.jpg', benefits:['Quick spray & wipe shine','Removes light dust & fingerprints','Adds gloss & slickness','Safe on paint, glass & trim'], desc:'A fast-acting spray detailer that removes light dust, fingerprints and smears with a simple spray and wipe — enhancing gloss and adding a protective slickness to all exterior surfaces.', scent:null, sku:'QDT-500-058', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'500ml',price:0,stock:50},{name:'1L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'dura-glaze', name:'Dura Glaze', cat:'car', sub:'Long-Lasting Paint Glaze & Sealant', price:0, was:null, size:'5L', rating:4.8, reviews:0, badge:null, img:'assets/products/dura-glaze.jpg', benefits:['Deep gloss & wet-look finish','Long-lasting paint protection','Fills fine scratches & swirls','Easy wipe-on wipe-off application'], desc:'A durable paint glaze and sealant that fills fine scratches, enhances depth and delivers a long-lasting wet-look gloss finish — protecting paintwork from UV, water and environmental contaminants.', scent:null, sku:'DGZ-5L-059', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:0,stock:50},{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'medium-cut', name:'Medium-Cut', cat:'car', sub:'Medium Cut Compound for Paint Correction', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/medium-cut.jpg', benefits:['Removes moderate scratches & oxidation','Levels paint surface effectively','For machine & hand application','Prepares paint for finishing polish'], desc:'A medium-cut polishing compound formulated to remove moderate scratches, oxidation and paint defects — levelling the surface and preparing it for a fine finishing polish and final protection step.', scent:null, sku:'MDC-5L-060', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:0,stock:50},{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'high-cut', name:'High-Cut', cat:'car', sub:'Heavy Cutting Compound for Severe Paint Defects', price:0, was:null, size:'5L', rating:4.7, reviews:0, badge:null, img:'assets/products/high-cut.jpg', benefits:['Heavy cutting power','Removes deep scratches & sanding marks','Restores neglected paintwork','For machine polisher use'], desc:'A high-cut compound with aggressive cutting power designed to remove deep scratches, heavy oxidation and sanding marks — restoring severely neglected paintwork and preparing it for medium and fine polishing stages.', scent:null, sku:'HGC-5L-061', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'1L',price:0,stock:50},{name:'5L',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
  { id:'burnishing-compound', name:'Burnishing Compound', cat:'car', sub:'Fine Burnishing Compound for High Gloss Finish', price:0, was:null, size:'500g', rating:4.8, reviews:0, badge:null, img:'assets/products/burnishing-compound.jpg', benefits:['Ultra-fine finishing compound','High-gloss mirror finish','Removes fine haze & buffer marks','For final polishing stage'], desc:'An ultra-fine burnishing compound designed for the final polishing stage — removing light haze, fine buffer marks and micro-scratches to deliver a brilliant mirror-like gloss finish.', scent:null, sku:'BNC-500-062', stock:50, lowStockThreshold:10, status:'active', variants:[{name:'500g',price:0,stock:50},{name:'1kg',price:0,stock:50}], createdAt:1749427200000, updatedAt:1749427200000 },
];

async function getProducts() {
  const stored = await readBlob(PRODUCTS_PATH);
  if (Array.isArray(stored) && stored.length) {
    const storedIds = new Set(stored.map(p => p.id));
    const newSeeds = SEED_PRODUCTS.filter(p => !storedIds.has(p.id));
    if (newSeeds.length) {
      const merged = [...stored, ...newSeeds];
      await writeBlob(PRODUCTS_PATH, merged);
      return merged;
    }
    return stored;
  }
  await writeBlob(PRODUCTS_PATH, SEED_PRODUCTS);
  return SEED_PRODUCTS;
}

module.exports = async function handler(req, res) {
  cors(res);
  if (req.method === 'OPTIONS') return res.status(204).end();

  // ── GET — public ──────────────────────────────────────────────────────────────
  if (req.method === 'GET') {
    const products = await getProducts();
    const list = req.query.all ? products : products.filter(p => p.status === 'active');
    return res.status(200).json(list);
  }

  const session = verifySession(req);
  if (!session) return res.status(401).json({ error: 'Unauthorized' });

  let body = req.body;
  if (typeof body === 'string') { try { body = JSON.parse(body); } catch { body = {}; } }

  // ── Normalise / clamp a product body before persisting ──────────────────────
  function sanitize(input) {
    const VALID_STATUS = ['active','draft','archived'];
    const VALID_CAT    = ['household','sanitiser','car','industrial'];
    const out = {};
    if (input.name      !== undefined) out.name      = String(input.name).trim().slice(0, 120);
    if (input.cat       !== undefined) out.cat       = VALID_CAT.includes(input.cat) ? input.cat : 'household';
    if (input.sub       !== undefined) out.sub       = String(input.sub).trim().slice(0, 200);
    if (input.price     !== undefined) out.price     = Math.max(0, Number(input.price) || 0);
    if (input.was       !== undefined) out.was       = input.was == null ? null : Math.max(0, Number(input.was) || 0);
    if (input.size      !== undefined) out.size      = String(input.size).trim().slice(0, 40);
    if (input.sku       !== undefined) out.sku       = String(input.sku).trim().slice(0, 60);
    if (input.scent     !== undefined) out.scent     = input.scent == null ? null : String(input.scent).slice(0, 80);
    if (input.badge     !== undefined) out.badge     = input.badge == null ? null : String(input.badge).slice(0, 40);
    if (input.img       !== undefined) out.img       = String(input.img).slice(0, 1024);
    if (input.desc      !== undefined) out.desc      = String(input.desc).slice(0, 4000);
    if (input.stock     !== undefined) out.stock     = Math.max(0, parseInt(input.stock, 10) || 0);
    if (input.lowStockThreshold !== undefined) out.lowStockThreshold = Math.max(0, parseInt(input.lowStockThreshold, 10) || 0);
    if (input.status    !== undefined) out.status    = VALID_STATUS.includes(input.status) ? input.status : 'draft';
    if (Array.isArray(input.benefits)) out.benefits  = input.benefits.filter(Boolean).slice(0, 10).map(b => String(b).slice(0, 200));
    if (Array.isArray(input.variants)) out.variants  = input.variants.slice(0, 12).map(v => ({
      name:  String(v.name || '').slice(0, 40),
      price: Math.max(0, Number(v.price) || 0),
      stock: Math.max(0, parseInt(v.stock, 10) || 0),
    }));
    return out;
  }

  // ── POST — create ─────────────────────────────────────────────────────────────
  if (req.method === 'POST') {
    const clean = sanitize(body);
    if (!clean.name)                return res.status(400).json({ error: 'Product name is required.' });
    if (!('price' in clean))        return res.status(400).json({ error: 'Price is required.' });
    if (!clean.sku)                 return res.status(400).json({ error: 'SKU is required.' });
    const products   = await getProducts();
    const newProduct = {
      rating: 4.8, reviews: 0,
      ...clean,
      id: Date.now().toString(),
      createdAt: Date.now(), updatedAt: Date.now(),
    };
    await writeBlob(PRODUCTS_PATH, [...products, newProduct]);
    return res.status(201).json(newProduct);
  }

  // ── PATCH — update ────────────────────────────────────────────────────────────
  if (req.method === 'PATCH') {
    const { id } = body;
    if (!id) return res.status(400).json({ error: 'Missing id' });
    const products = await getProducts();
    const idx      = products.findIndex(p => p.id === id);
    if (idx === -1) return res.status(404).json({ error: 'Not found' });
    const updated = { ...products[idx], ...sanitize(body), id, updatedAt: Date.now() };
    const newList  = [...products]; newList[idx] = updated;
    await writeBlob(PRODUCTS_PATH, newList);
    return res.status(200).json(updated);
  }

  // ── DELETE ────────────────────────────────────────────────────────────────────
  if (req.method === 'DELETE') {
    if (session.role !== 'admin') return res.status(403).json({ error: 'Admin only' });
    const { id } = body;
    if (!id) return res.status(400).json({ error: 'Missing id' });
    const products = await getProducts();
    await writeBlob(PRODUCTS_PATH, products.filter(p => p.id !== id));
    return res.status(200).json({ ok: true });
  }

  return res.status(405).json({ error: 'Method not allowed' });
};
